# Generated by Django 3.0.5 on 2022-10-31 13:47

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passport',
            field=models.FileField(null=True, upload_to=users.models.User.get_path, verbose_name='photo'),
        ),
    ]
