# Generated by Django 3.0.5 on 2022-11-11 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_activated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_activated',
        ),
    ]
