
"""
Django settings for metropol project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
from django.utils.timezone import timedelta
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SITE_NAME = "Zend Finance"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'h0eantw*e!)@@!q@&)j5k1!znc#m66&^-)349#4%+_=_@(822^'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

TEST_MODE = True

AUTO_LOGOUT = {
    'IDLE_TIME': timedelta(minutes=60),
    'REDIRECT_TO_LOGIN_IMMEDIATELY': True,
    'SESSION_TIME': timedelta(hours=1),
    'MESSAGE': 'Your session has expired. Please login again to continue.',
}  # logout after 10 minutes of downtime
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.humanize',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UsersConfig',
    'wallet.apps.WalletConfig',
    'company.apps.CompanyConfig',
    'core.apps.CoreConfig',
    # 3rdparty
    'whitenoise.runserver_nostatic',

    'crispy_forms',
    'crispy_bootstrap4',
    'djmoney',
    # 'phonenumber_field',

]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # whitenoise
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'metropol.middleware.AccountManagementMiddleware',
    'django_auto_logout.middleware.auto_logout',
    # language translation
    # 'django.middleware.locale.LocalMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'metropol.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'users/templates/dashboard'),
            os.path.join(BASE_DIR, 'templates/email'),
            os.path.join(BASE_DIR, 'users/templates/registration'),
            os.path.join(BASE_DIR, 'wallet/templates'),
            os.path.join(BASE_DIR, 'core/templates'),
            os.path.join(BASE_DIR, 'core/templates/email'),

        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'core.context.core',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # auto logout
                'django_auto_logout.context_processors.auto_logout_client',
            ],
        },
    },
]

WSGI_APPLICATION = 'metropol.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation

# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_REDIRECT_URL = 'dashboard'

LOGOUT_REDIRECT_URL = "index"

AUTH_USER_MODEL = 'users.User'

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

#LANGUAGE_CODE = 'es'

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'languages')
]

TIME_ZONE = 'UTC'

INTERNATIONAL_TRANSFER_CHARGE = 1

INTERNAL_TRANSFER_CHARGE = 1

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

MEDIA_URL = '/media/'


MEDIA_ROOT = os.path.join(BASE_DIR, "media")


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]

STATIC_ROOT = os.path.join(BASE_DIR, "asset")

STATIC_URL = '/static/'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# TWILLO
TWILLO_ACCOUNT_SID = 'AC213bba1c05225bedc1ebccccd8dbd9e0'
TWILLO_AUTH_TOKEN = '8512ae91f275f2bf0c8bf864e61692f3'
SMS_PHONE_NUMBER = '+19709866198'

# EMAIL FOR GMAIL
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_USE_TLS = True
#EMAIL_PORT = 587
#EMAIL_HOST_USER = 'geeetech.inc@gmail.com'
#EMAIL_HOST_PASSWORD = 'oehfphhfktpoezyh'


#GODADDY
#username : hmdzhamad@gmail.com
#email :hmdzhamad@gmail.com
#password : #@Hamadzz


# EMAIL FOR ZOHO
EMAIL_HOST = "smtp.zoho.com"
EMAIL_HOST_USER_SUPPORT = "support@metroscapitalbank.com"
EMAIL_HOST_USER_TRANSACTION = "transaction@metroscapitalbank.com"

# for other emails
EMAIL_HOST_USER = "support@metroscapitalbank.com"
DEFAULT_FROM_EMAIL = "support@metroscapitalbank.com"
EMAIL_HOST_PASSWORD = "#@Morris2390"

EMAIL_PORT = "587"
EMAIL_USE_TLS = "True"
#EMAIL_USE_SSL = "False"

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
