# Generated by Django 3.0.5 on 2022-07-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_transactions', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date']},
        ),
    ]
