# Generated by Django 3.0.5 on 2022-07-16 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=5)),
                ('symbol', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_pin', models.CharField(default='0000', max_length=6)),
                ('otp', models.CharField(blank=True, max_length=8, null=True)),
                ('balance', models.FloatField(default=0.0)),
                ('available_balance', models.FloatField(default=0.0)),
                ('allowed_to_transact', models.BooleanField(default=True)),
                ('disallow_reason', models.TextField(blank=True)),
                ('is_frozen', models.BooleanField(default=False)),
                ('credit_card_blocked', models.BooleanField(default=False)),
                ('credit_card_blocked_reason', models.TextField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='wallet.Currency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('amount', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=10)),
                ('nature', models.CharField(choices=[('Withdrawal', 'Withdrawal'), ('Deposit', 'Deposit'), ('Internal Transfer', 'Internal Transfer'), ('Domestic Transfer', 'Domestic Transfer'), ('International Transfer', 'International Transfer')], max_length=32)),
                ('status', models.CharField(choices=[('Failed', 'Failed'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Successful', 'Successful')], max_length=10)),
                ('description', models.TextField(null=True)),
                ('status_message', models.TextField()),
                ('charge', models.FloatField(blank=True, default=0.0)),
                ('iban', models.CharField(blank=True, max_length=40, null=True)),
                ('bic', models.CharField(blank=True, max_length=40, null=True)),
                ('swift_number', models.CharField(blank=True, max_length=30, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('account_name', models.CharField(blank=True, max_length=40, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('is_failed', models.BooleanField(default=False)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('new_date', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_receiver', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-new_date'],
            },
        ),
    ]
