# Generated by Django 3.0.5 on 2022-11-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20221031_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('failed', 'failed'), ('pending', 'pending'), ('srocessing', 'Processing'), ('successful', 'successful')], max_length=10),
        ),
    ]
