# Generated by Django 3.0.5 on 2022-11-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_auto_20221104_1809'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTransactionDetail',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date_approved',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='failure_reason',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_failed',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='nature',
            field=models.CharField(choices=[('Withdrawal', 'Withdrawal'), ('Deposit', 'Deposit'), ('Internal Transfer', 'Internal Transfer'), ('Domestic Transfer', 'Domestic Transfer'), ('International Transfer', 'International Transfer'), ('Bonus', 'Bonus')], max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
