# Generated by Django 3.0.5 on 2022-11-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20221108_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mail_is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
