# Generated by Django 4.1.7 on 2023-03-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_wallet_bills_wallet_savings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='bills',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='savings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
