# Generated by Django 4.1.7 on 2023-07-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_alter_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='allowed_to_transact',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='disallow_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('failed', 'failed'), ('pending', 'pending'), ('processing', 'Processing'), ('successful', 'successful')], max_length=10),
        ),
    ]
