# Generated by Django 4.1.7 on 2023-10-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_wallet_allowed_to_transact_wallet_disallow_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoAccountDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=50)),
                ('iban', models.CharField(max_length=50)),
                ('swift_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('failed', 'failed'), ('pending', 'pending'), ('processing', 'Processing'), ('successful', 'successful')], default='failed', max_length=10),
        ),
    ]
